# Generated by cucumber-sinatra. (Tue Mar 06 19:27:14 +0200 2012)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'application.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'ruby-debug'

Capybara.app = PuavoMoodleIntegration

class PuavoMoodleIntegrationWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  PuavoMoodleIntegrationWorld.new
end
